runtime: python39
entrypoint: gunicorn -b :$PORT catalogue:app

runtime_config:
  python_version: 3.9

env_variables:
  KEY: VALUE

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

# Add other settings as needed

