steps:
# Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/flaskapp', '.']

# Push the Docker image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/flaskapp']

- name: 'gcr.io/cloud-builders/gcloud:349.0.0'
  args: ['app', 'deploy']

# Clean up (optional)
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'cleanup']

